name: Integration Test
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: actions/checkout@v2
      
      - name: Check Dependabot Alerts
        id: alerts
        uses: spicyparrot/check-dependabot@trunk        #Check out yourself to test
        with:
          github_personal_token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}  

      - name: View Outputs
        run: |
          echo "::warning ::${{steps.alerts.outputs.total_alerts}} Open Vulnerability Alerts"
          echo "::warning ::${{steps.alerts.outputs.critical_alerts}} Critical Alerts "
          echo "::warning ::${{steps.alerts.outputs.high_alerts}} High Alerts"
          echo "::warning ::${{steps.alerts.outputs.moderate_alerts}} Moderate Alerts"
          echo "::warning ::${{steps.alerts.outputs.lower_alerts}} Low Alerts"
